Bump jQuery for picky Firefox
For 1.10 Firefox 28 throws a SyntaxError:
SyntaxError: Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead

I’m afraid that’s going to break a lot of the web!